### ISSUE TITLE
Request failed with status code 500. For more details check the error log in /src/log/installer.log file during Install Process

### ISSUE THREAD

**Issue by dzenanh** [orangehrm/orangehrm#1501] opened 2022-10-20 09:50 UTC
**Environment details**
OrangeHRM version: 5.1
OrangeHRM source: Sourceforge
Platform: Linux hrmtools 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PHP version: PHP 7.4.32 (cli) (built: Sep 29 2022 22:25:17) ( NTS )
Database and version: mysql  Ver 15.1 Distrib 10.6.7-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
Web server: Apache/2.4.52

If applicable:
Browser: Chrome

**Describe the bug**
"Request failed with status code 500. For more details check the error log in /src/log/installer.log file" at Creating configuration files Step.

**To Reproduce**
Error during install process

**Expected behavior**
Sucessfull install.

**What do you see instead:**
I see an error "Request failed with status code 500. For more details check the error log in /src/log/installer.log file" at the 8 step of the installation process.

If issue related to installation:
- src/log/installer.log
[2022-10-20T03:33:40.126663-05:00] installer.ERROR: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution [] []
[2022-10-20T03:33:40.126764-05:00] installer.ERROR: #0 /var/www/html/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1757): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(343): Doctrine\DBAL\Connection->convertException() #3 /var/www/html/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(405): Doctrine\DBAL\Connection->connect() #4 /var/www/html/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(367): Doctrine\DBAL\Connection->getDatabasePlatformVersion() #5 /var/www/html/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(284): Doctrine\DBAL\Connection->detectDatabasePlatform() #6 /var/www/html/orangehrm/src/lib/orm/Doctrine.php(78): Doctrine\DBAL\Connection->getDatabasePlatform() #7 /var/www/html/orangehrm/src/lib/orm/Doctrine.php(104): OrangeHRM\ORM\Doctrine->__construct() #8 /var/www/html/orangehrm/src/lib/orm/Doctrine.php(114): OrangeHRM\ORM\Doctrine::getInstance() #9 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/ConfigFileAPI.php(67): OrangeHRM\ORM\Doctrine::getEntityManager() #10 /var/www/html/orangehrm/installer/Controller/Installer/Api/ConfigFileAPI.php(47): OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI->handlePost() #11 /var/www/html/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Installer\Api\ConfigFileAPI->handlePost() #12 /var/www/html/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #13 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #14 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #15 /var/www/html/orangehrm/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #16 /var/www/html/orangehrm/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #17 {main} [] []

**Additional context**
Same goes with the orangeHRM ver. 5.2.

**Comment by RajithaKumara** [comment] 2022-10-21 08:11
Hi @dzenanh 
Seems this issue duplicate of #1344.
Can you check [this](https://github.com/orangehrm/orangehrm/issues/1344#issuecomment-1170950958).

**Comment by dzenanh** [comment] 2022-10-21 08:21
Hi @RajithaKumara 

I don't use docker. MySQL server is running locally. Do you have any clues? 
The same happens with all 5.x versions.

I have successfully installed the version 4.10.1 & 4.10.

**Comment by prcctv** [comment] 2022-10-21 14:23
> Hi @RajithaKumara
> 
> I don't use docker. MySQL server is running locally. Do you have any clues? The same happens with all 5.x versions.
> 
> I have successfully installed the version 4.10.1 & 4.10.

me too, It looks like we're experiencing the same bug

**Comment by RajithaKumara** [comment] 2022-10-21 17:38
@dzenanh I wanted to point out [this stackoverflow question](https://stackoverflow.com/questions/30182984/sqlstatehy000-2002-php-network-getaddresses-getaddrinfo-failed-name-or-ser).

In detailed; from 4.x to 5.x main change in installer related to this is,
in 4.x: used [`mysqli`](https://www.php.net/manual/en/book.mysqli.php) in installer, application used [`PDO`](https://www.php.net/manual/en/book.pdo.php)
in 5.x: both installer and application used `PDO`

**Comment by prcctv** [comment] 2022-10-22 01:58
Thank you very much for your reply. I just don't know how to handle it yet, do I need to modify PHP.INI?

> @dzenanh I wanted to point out [this stackoverflow question](https://stackoverflow.com/questions/30182984/sqlstatehy000-2002-php-network-getaddresses-getaddrinfo-failed-name-or-ser).
> 
> In detailed; from 4.x to 5.x main change in installer related to this is, in 4.x: used [`mysqli`](https://www.php.net/manual/en/book.mysqli.php) in installer, application used [`PDO`](https://www.php.net/manual/en/book.pdo.php) in 5.x: both installer and application used `PDO`

**Comment by RajithaKumara** [comment] 2022-10-22 03:46
I dig into the error log. It seems the application is fully installed. not an issue with the installer. At the final step, the installer checks the real database connection after writing the configuration file. 
You can give a try by accessing the login page directly;
`https://orangehrm.domain.com/web/index.php/auth/login`

But if that also failed. please provide `src/log/orangehrm.log`.

Also just check [this](https://stackoverflow.com/questions/60115668/symfony-5-sqlstatehy000-2002-php-network-getaddresses-getaddrinfo-failed). Is your MySQL user password contains `@` sign?

**Comment by prcctv** [comment] 2022-10-22 04:56
> I dig into the error log. It seems the application is fully installed. not an issue with the installer. At the final step, the installer checks the real database connection after writing the configuration file. You can give a try by accessing the login page directly; `https://orangehrm.domain.com/web/index.php/auth/login`
> 
> But if that also failed. please provide `src/log/orangehrm.log`.
> 
> Also just check [this](https://stackoverflow.com/questions/60115668/symfony-5-sqlstatehy000-2002-php-network-getaddresses-getaddrinfo-failed). Is your MySQL user password contains `@` sign?

Yes, you are wonderful.
There were "#"  in the password,  it  works perfectly at once after resetting. 
Thank you very much!

**Comment by RajithaKumara** [comment] 2022-10-23 02:27
Thanks @prcctv @dzenanh for raising this issue. Will mark this as a bug in the application and will be solved in the next release.

**Comment by dzenanh** [comment] 2022-10-23 14:54
@prcctv do I get you right, you removed '#' from the password and the exception is resolved?

**Comment by prcctv** [comment] 2022-10-24 06:20
> @prcctv do I get you right, you removed '#' from the password and the exception is resolved?

Yes, my DB root user  and Ohrm user passwords all contain '#' which breaks parsing, changing the passwords to not have the symbol  then the installation completed without any problems.

**Comment by dzenanh** [comment] 2022-10-24 08:07
thanks @prcctv and @RajithaKumara . It works now.

**Closed** 2022-10-25 10:47 UTC
Labels: bug, 5x

**Comment by RajithaKumara** [comment] 2022-12-29 04:06
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).
