### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by abicomputersh** [orangehrm/orangehrm#607] opened 2020-02-19 10:54 UTC
Error line
Warning: require(C:\xampp\htdocs\hrm\installer\environmentCheck/../../symfony/lib/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\hrm\installer\environmentCheck\SystemValidator.php on line 22

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\hrm\installer\environmentCheck/../../symfony/lib/vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\hrm\installer\environmentCheck\SystemValidator.php on line 22

autoload.php not in the folder

**Comment by RajithaKumara** [comment] 2020-02-19 11:06
Hi @abicomputersh 
Please wrap [this](https://github.com/orangehrm/orangehrm/blob/master/installer/environmentCheck/SystemValidator.php#L22) line with `realpath()` as a temporary fix.

i.e. `require realpath(__DIR__ . "/../../symfony/lib/vendor/autoload.php");`

Thank you for raising this issue. We'll fix this in next release.

**Comment by abicomputersh** [comment] 2020-02-19 11:20
is the autoload.php available anywhere

**Comment by RajithaKumara** [comment] 2020-02-19 11:25
@abicomputersh if you use [OrangeHRM from sourceforge](https://sourceforge.net/projects/orangehrm/) then `autoload.php` should be there. In your case the issue is Windows use `\` as directory separator.

**Comment by abicomputersh** [comment] 2020-02-19 19:17
Halo,got it, though it's not this \,I had tried that before.let me try the
sourceforge one

**Comment by kavithagurusamy** [comment] 2021-01-05 08:21
Fixed in OrangeHRM 4.3.5 version

**Closed by kavithagurusamy** 2021-01-05 08:21 UTC
