### ISSUE TITLE
Not able to login as admin

### ISSUE THREAD

**Issue by ashwithpoojary98** [orangehrm/orangehrm#1091] opened 2022-01-11 15:42 UTC
**Environment details**
OrangeHRM version: [e.g. 4.3, 4.3.4]
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows), or Docker
PHP version: output of `php -v`
Database and version: [e.g. MySQL 5.7, MariaDB 10.2]
Web server: [e.g. Apache 2.4, Nginx 1.4]

If applicable:
Browser: [e.g. Chrome, Safari]

**Describe the bug**
Please describe what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Please describe what you expected to happen.

**What do you see instead:**
Provide error logs depending on the issue.

If issue related to installation:
- installer/log.txt
- logInsatall.log

If issue related to any other
- symfony/log/orangehrm.log 

**Screenshots**

**Additional context**

**Comment by RajithaKumara** [comment] 2022-01-12 07:09
Hi @ashwithpoojary98 
The issue is not clear. Please update this with steps to reproduce.

**Comment by samanthajayasinghe** [comment] 2022-03-22 07:35
closing since no reproduce steps

**Closed by samanthajayasinghe** 2022-03-22 07:35 UTC
