### ISSUE TITLE
Centos 7 install 

### ISSUE THREAD

**Issue by Utente81** [orangehrm/orangehrm#702] opened 2020-12-30 14:57 UTC
I try to install orangehrm in centos 7 with this prerequisites (apache,php7.2,mariadb), but when the web installation control the prerequisities the directory lib and sinfony we see an error (NO WRITABLE). I change the permission to 755 from 777 and change owner to apache in nobody but the error remaining.

**Comment by RajithaKumara** [comment] 2021-01-01 07:41
Closing because this duplicate of  #701

**Closed by RajithaKumara** 2021-01-01 07:41 UTC
Labels: duplicate
