### ISSUE TITLE
Employee search with filter status 'Active' also shows 'Inactive' employees

### ISSUE THREAD

**Issue by arjun7208** [orangehrm/orangehrm#594] opened 2019-11-12 05:41 UTC
Dear Team,

can you help me with the following issue? my Orangehrm version is 4.1

in PIM-->Employee List when I search for employees by Selecting only 'Active'  as an Employment Status then it also shows an employees with 'Inactive' status. 

![empl_list](https://user-images.githubusercontent.com/56362438/68645158-26c7e580-053d-11ea-89f3-45a4d849f5ea.png)

**Comment by Damith88** [comment] 2019-11-12 06:07
Hi @arjun7208 
I was unable to reproduce the issue you face.
you have to click search button once you set the filters.
have you clicked search button after setting the 'employment status' filter to 'active'?

**Comment by Damith88** [comment] 2019-11-12 06:08
Hi @arjun7208 
I was unable to reproduce the issue you are having.
To filter the list, you have to click search button once you set the filters.
have you clicked search button after setting the 'employment status' filter to 'active'?

**Comment by arjun7208** [comment] 2019-11-12 07:33
Hello Sir,

Yes, I am clicking on Search button after setting the filters. I have even selected 'Current Employees only' but still it shows Inactive employees.

However, if I search for 'Inactive' employees then results shows only the list of Inactive employees.


Thanking you!

Warm Regards

Arjun Madhav

**Comment by kavithagurusamy** [comment] 2019-11-13 12:56
Hi Arjun

We have checked the issue and was not able to reproduce it. Have you done any customization to 4.1 version? Is the data loaded or manually entered into the system? Have you upgraded this version from any of the previous versions?
We might need to have a session to check as why the issue is occurring. 

Please drop an email with the git issue no to "support@orangehrm.com" with the subject as **OpenSource - 4.1 - Employee Filter Issue** to arrange the session to troubleshoot this issue.

Regards
Kavitha

**Comment by kavithagurusamy** [comment] 2019-11-21 09:21
Hi Arjun

I am closing the issue as per our session, The issue is occurred due to incorrect ids saved for the employment status. 

Regards
Kavitha

**Closed by kavithagurusamy** 2019-11-21 09:21 UTC
