### ISSUE TITLE
Approving multiple leaves after cancellation of few

### ISSUE THREAD

**Issue by arjun7208** [orangehrm/orangehrm#576] opened 2019-10-09 17:30 UTC
When employee applies for multiple leaves and if few of them are cancelled (either by Admin or by employee itself) and after that if pending ones are approved then it approves the cancelled leaves as well. Though system sends email of cancellation of leaves and the leaves get actually cancelled in system.

**Comment by kavithagurusamy** [comment] 2019-10-10 09:52
@arjun7208 
This is confirmed as bug in the system. We will get this fixed in our next release which is scheduled for the community at the end of October.
Please let me know whether you require the fix urgently, We will be able to send you the patch for your version. Please let me know the OrangeHRM version you are using if you require the patch at your version.

**Comment by arjun7208** [comment] 2019-10-10 09:55
Hello Team,

Thank you for prompt response!

Would be of great help if you can send me the patch for the same :) as we need this to be fixed urgently.




Thanking you!

Warm Regards

Arjun Madhav
Software Assistant (ICT Admin)
HILL SPRING INTERNATIONAL SCHOOL


M.P. Mills Compound,

B.B. Nakashe Marg,

Tardeo,  Mumbai-400034

Tel -  +91-22-2355 6201<tel:+91-22-2355%206201>


Ext no - 185
Location: IBDP E-wing, 6th Flr, Publications Block.
________________________________

**Comment by arjun7208** [comment] 2019-10-10 10:58
Our Orangehrm Version is 4.1


Thanking you!

Warm Regards

Arjun Madhav
________________________________

**Comment by kavithagurusamy** [comment] 2019-10-11 08:02
Arjun

The fix is under QA. We will keep you updated once the fix is approved.

https://github.com/orangehrm/orangehrm/pull/577

**Comment by kavithagurusamy** [comment] 2019-10-15 05:28
Arjun

The patch is available for this issue. You can follow the below instructions to apply the patch manually. Please backup your files before replacement these files.

**Step 1:**  _Replace this file with <orangehrm root directory>symfony/plugins/orangehrmLeavePlugin/lib/model/doctrine/PluginLeaveRequest.class.php

https://raw.githubusercontent.com/orangehrm/orangehrm/4.3.4/symfony/plugins/orangehrmLeavePlugin/lib/model/doctrine/PluginLeaveRequest.class.php
 
**Step 2:**    _Replace this file with <orangehrm directory>symfony/plugins/orangehrmLeavePlugin/lib/model/doctrine/PluginLeaveRequest.class.php 

https://raw.githubusercontent.com/orangehrm/orangehrm/4.3.4/symfony/plugins/orangehrmLeavePlugin/modules/leave/actions/viewLeaveListAction.class.php

**Comment by arjun7208** [comment] 2019-10-16 06:05
Dear Team,

Thank you for the patch. I assume that by mistake the path mentioned in the Step 2 was same as that was in Step 1. I have updated the mentioned files and the issue has been fixed now.


Thanks again for all the help and support!


Warm Regards

Arjun Madhav
Software Assistant (ICT Admin)
HILL SPRING INTERNATIONAL SCHOOL


M.P. Mills Compound,

B.B. Nakashe Marg,

Tardeo,  Mumbai-400034

Tel -  +91-22-2355 6201<tel:+91-22-2355%206201>


Ext no - 185
Location: IBDP E-wing, 6th Flr, Publications Block.
________________________________

**Comment by kavithagurusamy** [comment] 2019-10-16 06:29
Yes, The path was updated in the post after noting that it was updated incorrectly in the original post.

Great to know the issue is solved at your end.

**Closed by kavithagurusamy** 2019-10-16 06:29 UTC
Labels: Fixed, bug
