### ISSUE TITLE
CSS links are broken

### ISSUE THREAD

**Issue by Engineerumair** [orangehrm/orangehrm#611] opened 2020-02-26 13:57 UTC
I have deployed your application in aws Docker container through Jenkins, but the CSS files are not fetched.

here is the url for my website : [Link](https://34.200.67.249/symfony/web/index.php/auth/login)

and here is the error : 

> Refused to apply style from 'https://34.200.67.249/symfony/web/var/www/html/symfony/web/themes/default/css/reset.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Can you please help?

**Comment by RajithaKumara** [comment] 2020-02-27 03:13
Hi @Engineerumair 
Duplicate issue of #584 
We need to further investigate since we can't reproduce the issue.
Can you provide more information about Docker container. i.e. Operating System, PHP version, Database and version

**Comment by Engineerumair** [comment] 2020-02-27 05:25
But that issue is also not resolved but I found  one file is missing in repo (symfony\web) and they are included in release, here are the files : 
resource_dir_inc.php
and one directory (webres_5dba87d44c2636.77253203)

**Comment by RajithaKumara** [comment] 2020-03-05 12:08
Hi @Engineerumair 
Actually `symfony/web` directory is different in [GitHub repo](https://github.com/orangehrm/orangehrm) and [production releases](https://sourceforge.net/projects/orangehrm/files/stable/). We use this approach to avoid browser caching issues when you upgrade OrangeHRM from one to new release. Refer [this](https://github.com/orangehrm/orangehrm/issues/584#issuecomment-595191719) for more.

**Comment by kavithagurusamy** [comment] 2021-01-05 08:19
Fixed in OrangeHRM 4.3.5 version

**Closed by kavithagurusamy** 2021-01-05 08:19 UTC
