### ISSUE TITLE
Unable to launch OrangeHRM 5.5

### ISSUE THREAD

**Issue by karthick4055** [orangehrm/orangehrm#1717] opened 2023-07-11 10:45 UTC
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: https://github.com/orangehrm/orangehrm/releases/download/v5.5/orangehrm-5.5.zip
- Platform: Oracle Linux
- PHP version: 8.1
- Database and version: MySQL 5.7
- Web server: Apache 2.4
- Browser: Chrome

### Describe the bug

Hello,

I have successfully installed OrangeHRM 5.5. Once the installation is completed, While we click the Launch OrangeHRM, it's redirected to the Installation page again. Not able to locate the Login page URL. Please help with this
![image](https://github.com/orangehrm/orangehrm/assets/139221501/96cc0816-9d57-44cf-8322-f42a29a69972)

**Comment by karthick4055** [comment] 2023-07-11 13:41
Hello,

We are installing this on Oracle Linux 7.9 which is running on Virtualbox.

**Comment by dskachan** [comment] 2023-07-12 21:05
The same on my side - I'm installing it using docker-compose on my hw
the same behavior with versions 5.5 and 5.4

**Comment by ksmtkmr** [comment] 2023-07-15 08:06
I'm having the same issue. Tried a manual install and via docker compose on ubuntu 22.04

**Comment by RajithaKumara** [comment] 2023-07-15 08:26
Hi,
we are working on this issue, for the moment we could not reproduce with our environment, bit still we are working on this.
Can you check [this thread](https://github.com/orangehrm/orangehrm/issues/1499#issuecomment-1286557419), you might find   extra details.

**Comment by devishke-orange** [comment] 2023-07-17 08:42
Hi @karthick4055 @dskachan

From my testing on Oracle Linux 7, it seems the issue is being caused due to the slow speed of migrations. If the migrations proceed slowly enough, the progress bar will reach 100% and the "Next" button will be shown prematurely (before all the installation steps are completed).

As stated by @RajithaKumara you can try the CLI installer located in the `installer` folder. Another solution would be to wait until all the steps have been completed before clicking "Next". I have included a screenshot below for reference:

![image](https://github.com/orangehrm/orangehrm/assets/97493184/a71c26c8-0254-4a69-8472-17dfd6b826ff)

Once the web installer reaches this state, you can click "Next" and you should be redirected to the login page when clicking "Launch OrangeHRM" on the subsequent page.

Please let us know if the issue persists after trying this.

**Comment by Poachedegg** [comment] 2023-07-18 08:01
一样的问题，先是卡住，然后我等了半小时后之后点击next，于是到了最后一步
![image](https://github.com/orangehrm/orangehrm/assets/28036120/b4519468-2f49-49de-a8af-ae030ea48cb9)
但是当我点击了完成安装后，它又到了安装首页
![image](https://github.com/orangehrm/orangehrm/assets/28036120/892bc30e-16d6-44de-91d2-2266b446bfef)

**Comment by devishke-orange** [comment] 2023-07-18 09:24
Hello @Poachedegg. Can you give me the following details please?

Operating System:
PHP version:
Database:
Web server:
Internet  Browser:

You can also try installing from the CLI.

Translation from Google Translate:
你好@PoachedEgg。 您能给我以下详细信息吗？

操作系统：
PHP版本：
数据库：
网络服务器：
网络浏览器：

您还可以尝试从 CLI 安装

**Comment by Poachedegg** [comment] 2023-07-18 10:53
> 你好 .你能给我以下细节吗？
> 
> 操作系统： PHP 版本： 数据库： Web 服务器： 互联网浏览器：
> 
> 您也可以尝试从 CLI 安装。
> 
> 翻译自谷歌翻译： 你好。您能给我以下详细信息吗？
> 
> 操作系统： PHP版本： 数据库： 网络服务器： 网络浏览器：
> 
> 您还可以尝试从 CLI 安装

不好意思贴上环境了
是用docker-compose.yml去安装的
centos7.6+php7.4+mongdb10.0

version: '3'

services:
  orangehrm:
    image: orangehrm/orangehrm:latest
    container_name: orangehrm
    restart: unless-stopped
    ports:
      - 8202:80
    volumes:
      - ./data:/orangehrm
    environment:  
      - PUID=1000
      - PGID=1000

and chmod 777 ./data

**Comment by devishke-orange** [comment] 2023-07-18 11:30
Thank you! We will look into this issue further.
谢谢你！ 我们将进一步研究这个问题。

**Comment by zhangweimtan** [comment] 2023-07-19 00:40
> > 你好 .你能给我以下细节吗？
> > 操作系统： PHP 版本： 数据库： Web 服务器： 互联网浏览器：
> > 您也可以尝试从 CLI 安装。
> > 翻译自谷歌翻译： 你好。您能给我以下详细信息吗？
> > 操作系统： PHP版本： 数据库： 网络服务器： 网络浏览器：
> > 您还可以尝试从 CLI 安装
> 
> 不好意思贴上环境了 是用docker-compose.yml去安装的 centos7.6+php7.4+mongdb10.0
> 
> version: '3'
> 
> services: orangehrm: image: orangehrm/orangehrm:latest container_name: orangehrm restart: unless-stopped ports: - 8202:80 volumes: - ./data:/orangehrm environment: - PUID=1000 - PGID=1000
> 
> and chmod 777 ./data

一样的问题，看了https://wbsu2003.gitee.io/2023/07/17/%E5%BC%80%E6%BA%90%E4%BA%BA%E5%8A%9B%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FOrangeHRM/，安装就出现了问题，5.4,5.5都不行

**Comment by devishke-orange** [comment] 2023-07-19 02:22
Hi @zhangweimtan. Thank you for providing your setup process. We are looking into this issue currently.

你好@zhangweimtan。 感谢您提供设置过程。 我们目前正在研究这个问题。

**Comment by zhangweimtan** [comment] 2023-07-19 04:56
> Hi @zhangweimtan. Thank you for providing your setup process. We are looking into this issue currently.
> 
> 你好@zhangweimtan。 感谢您提供设置过程。 我们目前正在研究这个问题。

i have succussed running orangehrm web( when access to MySQL, i used root). however, it appears i could not set simplified Chinese in Localization, only shows traditional Chinese.

**Comment by kavithagurusamy** [comment] 2023-08-11 03:41
Closing the ticket as the provided solution for the issue is working

**Closed by kavithagurusamy** 2023-08-11 03:41 UTC
Labels: bug, 5x
